version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: marquez-postgres
    environment:
      POSTGRES_DB: marquez
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marquez"]
      interval: 10s
      timeout: 5s
      retries: 5

  marquez:
    image: marquezproject/marquez:0.46.0
    container_name: marquez
    environment:
      MARQUEZ_CONFIG: /config/marquez.yml
      MARQUEZ_DATABASE_URL: postgresql://marquez:marquez@postgres:5432/marquez
      MARQUEZ_DATABASE_USER: marquez
      MARQUEZ_DATABASE_PASSWORD: marquez
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./marquez-config.yml:/config/marquez.yml:ro
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/namespaces"]
      interval: 30s
      timeout: 10s
      retries: 5

  marquez-web:
    image: marquezproject/marquez-web:0.46.0
    container_name: marquez-web
    environment:
      MARQUEZ_HOST: marquez
      MARQUEZ_PORT: 5000
    ports:
      - "3000:3000"
    depends_on:
      marquez:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  default:
    name: marquez-network